### ISSUE TITLE
Unable to create Department object that contains Employee objects

### ISSUE THREAD

**Issue by jboblitt** [jboblitt/crest-hr#1]
I am unable to create Department object that contains Employee objects.

#### Request:
`http://localhost/api/departments/3` using Postman client

#### Response 
```
{"id":3,"version":0,"name":"Computer Science","identifier":"CS","employees"}
```
#### Error message
```
traefik_1     | time="2018-04-15T18:29:42Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/api/departments/3","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["c2486442-37a1-4c19-9966-e977fd9bbc16"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42770","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:29:42Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/api/departments/3","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["c2486442-37a1-4c19-9966-e977fd9bbc16"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42770","RequestURI":"/api/departments/3","TLS":null}" ForwardURL=http://10.4.0.4:8080 
traefik_1     | time="2018-04-15T18:29:42Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.4.0.4:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["c2486442-37a1-4c19-9966-e977fd9bbc16"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42770","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:29:42Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.4.0.4:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["c2486442-37a1-4c19-9966-e977fd9bbc16"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42770","RequestURI":"/api/departments/3","TLS":null}" 
wildfly_1     | 18:29:42,921 INFO  [stdout] (default task-61) Hibernate: select department0_.id as id1_0_0_, department0_.identifier as identifi2_0_0_, department0_.name as name3_0_0_, department0_.version as version4_0_0_ from Department department0_ where department0_.id=?
traefik_1     | time="2018-04-15T18:29:42Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://10.4.0.4:8080, code: 200, Length: 76, duration: 8.4814ms" 
traefik_1     | time="2018-04-15T18:29:42Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.4.0.4:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["c2486442-37a1-4c19-9966-e977fd9bbc16"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42770","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:29:42Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.4.0.4:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["c2486442-37a1-4c19-9966-e977fd9bbc16"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42770","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:29:42Z" level=debug msg="vulcand/oxy/roundrobin/rr: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/api/departments/3","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["c2486442-37a1-4c19-9966-e977fd9bbc16"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42770","RequestURI":"/api/departments/3","TLS":null}" 
wildfly_1     | 18:29:42,927 ERROR [io.undertow.request] (default task-61) UT005023: Exception handling request to /api/departments/3: org.jboss.resteasy.spi.UnhandledException: RESTEASY003770: Response is committed, can't handle exception
wildfly_1     | 	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:174)
wildfly_1     | 	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:478)
wildfly_1     | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:422)
wildfly_1     | 	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
wildfly_1     | 	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
wildfly_1     | 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
wildfly_1     | 	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
wildfly_1     | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
wildfly_1     | 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
wildfly_1     | 	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
wildfly_1     | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
wildfly_1     | 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
wildfly_1     | 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
wildfly_1     | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
wildfly_1     | 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
wildfly_1     | 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
wildfly_1     | 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
wildfly_1     | 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
wildfly_1     | 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
wildfly_1     | 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
wildfly_1     | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
wildfly_1     | 	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
wildfly_1     | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
wildfly_1     | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
wildfly_1     | 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
wildfly_1     | 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
wildfly_1     | 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
wildfly_1     | 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
wildfly_1     | 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
wildfly_1     | 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
wildfly_1     | 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
wildfly_1     | 	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
wildfly_1     | 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
wildfly_1     | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
wildfly_1     | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:805)
wildfly_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
wildfly_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
wildfly_1     | 	at java.lang.Thread.run(Thread.java:748)
wildfly_1     | Caused by: com.fasterxml.jackson.databind.JsonMappingException: failed to lazily initialize a collection of role: edu.vt.crest.hr.entity.DepartmentEntity.employees, could not initialize proxy - no Session (through reference chain: edu.vt.crest.hr.entity.DepartmentEntity["employees"])
wildfly_1     | 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:378)
wildfly_1     | 	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:338)
wildfly_1     | 	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:342)
wildfly_1     | 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:686)
wildfly_1     | 	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
wildfly_1     | 	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
wildfly_1     | 	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1428)
wildfly_1     | 	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:930)
wildfly_1     | 	at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:207)
wildfly_1     | 	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:131)
wildfly_1     | 	at org.jboss.resteasy.core.interception.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:60)
wildfly_1     | 	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:120)
wildfly_1     | 	at org.jboss.resteasy.security.doseta.DigitalSigningInterceptor.aroundWriteTo(DigitalSigningInterceptor.java:145)
wildfly_1     | 	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
wildfly_1     | 	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPEncodingInterceptor.aroundWriteTo(GZIPEncodingInterceptor.java:100)
wildfly_1     | 	at org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
wildfly_1     | 	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:98)
wildfly_1     | 	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:473)
wildfly_1     | 	... 44 more
wildfly_1     | Caused by: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: edu.vt.crest.hr.entity.DepartmentEntity.employees, could not initialize proxy - no Session
wildfly_1     | 	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:587)
wildfly_1     | 	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:204)
wildfly_1     | 	at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:148)
wildfly_1     | 	at org.hibernate.collection.internal.PersistentSet.size(PersistentSet.java:143)
wildfly_1     | 	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:102)
wildfly_1     | 	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
wildfly_1     | 	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
wildfly_1     | 	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
wildfly_1     | 	... 58 more
wildfly_1     | 
```

#### Expected Behavior
Return the following object:
```
{
    "id": 3,
    "version": 0,
    "name": "CS",
    "identifier": "Computer Science",
    "employees": [
        {
            "id": 10,
            "version": 0,
            "firstName": "Ada",
            "lastName": "Lovelace"
        },
        {
            "id": 11,
            "version": 0,
            "firstName": "Linus",
            "lastName": "Torvalds"
        }
    ]
}
```

**Comment by jboblitt** [comment]
#### Modifying the following code, I was able to manually create and return a new DepartmentEntity object which was parsed into JSON and returned correctly.  

#### From edu.vt.crest.hr.rest.DepartmentResource
```
@GET
	@Path("/{id:[0-9][0-9]*}")
	@Produces(MediaType.APPLICATION_JSON)
	public Response findById(@PathParam("id") Long id) {
//		DepartmentEntity department = departmentService.findById(id);
//		if (department != null)
//			return Response.ok(department).build();
//		else {
//			throw (new NoResultException("Error occurred finding DepartmentEntity by id: [" + id + "]"));
//		}

		DepartmentEntity department = new DepartmentEntity();
		department.setId(3l);
		department.setName("CS");
		department.setIdentifier("Computer Science");
		EmployeeEntity employee1 = new EmployeeEntity();
		employee1.setId(10l);
		employee1.setFirstName("Ada");
		employee1.setLastName("Lovelace");
		department.addEmployee(employee1);
		EmployeeEntity employee2 = new EmployeeEntity();
		employee2.setId(11l);
		employee2.setFirstName("Linus");
		employee2.setLastName("Torvalds");
		department.addEmployee(employee2);
		return Response.ok(department).build();
	}
```

#### From edu.vt.crest.hr.entity.DepartmentEntity
```
public void addEmployee(EmployeeEntity employee) {
		if (this.employees == null){
			this.employees = new LinkedHashSet<>();
		}
		this.employees.add(employee);
	}
```

#### Request 
`http://localhost/api/departments/3`

#### Response
```
{
    "id": 3,
    "version": 0,
    "name": "CS",
    "identifier": "Computer Science",
    "employees": [
        {
            "id": 10,
            "version": 0,
            "firstName": "Ada",
            "lastName": "Lovelace"
        },
        {
            "id": 11,
            "version": 0,
            "firstName": "Linus",
            "lastName": "Torvalds"
        }
    ]
}
```

#### Logging in consolse
```
traefik_1     | time="2018-04-15T18:48:15Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/api/departments/3","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["1d8ae385-f523-48f9-a9a6-12befec9223d"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42782","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:48:15Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL=http://10.4.0.4:8080 Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/api/departments/3","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["1d8ae385-f523-48f9-a9a6-12befec9223d"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42782","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:48:15Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.4.0.4:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["1d8ae385-f523-48f9-a9a6-12befec9223d"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42782","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:48:15Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.4.0.4:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["1d8ae385-f523-48f9-a9a6-12befec9223d"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42782","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:48:15Z" level=debug msg="vulcand/oxy/forward/http: Round trip: http://10.4.0.4:8080, code: 200, Length: 204, duration: 4.0068ms" 
traefik_1     | time="2018-04-15T18:48:15Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.4.0.4:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["1d8ae385-f523-48f9-a9a6-12befec9223d"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42782","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:48:15Z" level=debug msg="vulcand/oxy/forward: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"10.4.0.4:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["1d8ae385-f523-48f9-a9a6-12befec9223d"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42782","RequestURI":"/api/departments/3","TLS":null}" 
traefik_1     | time="2018-04-15T18:48:15Z" level=debug msg="vulcand/oxy/roundrobin/rr: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/api/departments/3","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Cache-Control":["no-cache"],"Connection":["keep-alive"],"Postman-Token":["1d8ae385-f523-48f9-a9a6-12befec9223d"],"User-Agent":["PostmanRuntime/7.1.1"]},"ContentLength":0,"TransferEncoding":null,"Host":"localhost","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.4.0.1:42782","RequestURI":"/api/departments/3","TLS":null}" 
```

So despite (1) the original exception including "com.fasterxml.jackson.databind.JsonMappingException" and (2) the original response cutting off the json object, this does not appear to be a json error (as proven in the above test).  So maybe the problem is in the JPA object relations.

**Comment by jboblitt** [comment]
Apparently the real issue is that Hibernate/JPA is trying to lazily load my Employee collection after the session has closed.

#### Solution 1

`<property name="hibernate.enable_lazy_load_no_trans" value="true"/>`

This is an anti-pattern though because any lazily loaded object will open an individual session, as mentioned here: https://vladmihalcea.com/the-hibernate-enable_lazy_load_no_trans-anti-pattern/

#### Solution 2

Always eagerly fetch the collection.
```
@OneToMany (fetch = FetchType.EAGER)
	@JoinColumn(name = "department_id", referencedColumnName = "id")
	private Set<EmployeeEntity> employees;
```
Not good for performance or for trying to return an object with only Basic attributes

#### Solution 3
Fetch join 
```
/**
   * {@inheritDoc}
   */
  @Override
  public DepartmentEntity findById(Long id) {
    String strQuery = "Select d from " + DepartmentEntity.ENTITY_NAME + " d left join fetch d.employees where d.id = :id";
    TypedQuery<DepartmentEntity> query = em.createQuery(strQuery, DepartmentEntity.class);
    query.setParameter("id", id);
    return query.getSingleResult();
  }
```

This could be hard to maintain if have many collections and permutations of collections that you need to return in different circumstances.

 - [part1](https://www.javacodegeeks.com/2012/07/four-solutions-to-lazyinitializationexc_05.html)
 - [part2](https://www.javacodegeeks.com/2012/07/four-solutions-to-lazyinitializationexc.html)
 - Which I found from this [stackoverflow](https://stackoverflow.com/questions/25362831/solve-hibernate-lazy-init-issue-with-hibernate-enable-lazy-load-no-trans)

#### Solution 4

Named Entity Graph 
 - Define a graph of entities that shall be queried from the database using annotations.
 - Single query 
 - Maintain a named entity graph for each combination of associations that shall be retrieved within one query
 - Found here: https://www.thoughts-on-java.org/5-ways-to-initialize-lazy-relations-and-when-to-use-them/

**Comment by jboblitt** [comment]
Using solution 3 above for now.
